### ISSUE TITLE
rake config should not overwrite files by default

### ISSUE THREAD

**Issue by mjobin-mdsol** [mdsol/dice_bag#21] opened 2012-11-26 17:37 UTC
rake config overwrite files with no warning... 
I think it should only push missing files automatically, display something when the file is already there.
and offer to diff/overwrite/skip when the content is different.

very much like rails do when you upgrade your app or when using the generator.

I think dice_bag is a great idea. and everywhere I saw people making .example files of their config. I think dice_bag should aimed at being very small and eventually become part of rails 4

so we should make it very much like rails does things for that reason.

**Comment by asmith-mdsol** [comment] 2012-11-27 09:53
This is a duplicate of #12 so closing.

**Closed as completed by asmith-mdsol** 2012-11-27 09:53 UTC
Labels: duplicate
